var gulp = require('gulp');
var htmlmin = require('gulp-html-minifier-terser');

function minifyHTML() {
	return gulp
		.src(['./dist/convosight-web-client/**/*.html'])
		.pipe(
			htmlmin({
				collapseBooleanAttributes: true,
				collapseInlineTagWhitespace: true,
				collapseWhitespace: true,
				continueOnParseError: true,
				decodeEntities: true,
				includeAutoGeneratedTags: true,
				minifyCSS: true,
				minifyJS: true,
				removeAttributeQuotes: true,
				removeComments: true,
				removeEmptyAttributes: true,
				removeOptionalTags: true,
				removeRedundantAttributes: true,
				sortClassName: true,
				sortAttributes: true,
				useShortDoctype: true
			})
		)
		.pipe(gulp.dest('./dist/convosight-web-client'));
}

var build = gulp.series(minifyHTML);

exports.default = build;
