export enum NotificationType {
	CsAppAdded = 'CsAppAdded',
	WelcomeNote = 'WelcomeNote',
	UrgentAlerts = 'UrgentAlerts',
	CouldNotPublishPost = 'CouldNotPublishPost',
	InstallationOfAppCompleted = 'InstallationOfAppCompleted',
	InstallationOfAppCompletedV2 = 'InstallationOfAppCompletedV2',
	UninstallationOfAppCompleted = 'UninstallationOfAppCompleted',
	UserCampaignTasksCreated = 'UserCampaignTasksCreated',
	ResharePost = 'ResharePost',
	DailyPostCountLessThanAverage = 'DailyPostCountLessThanAverage',
	ReactionsPerPostLowerThanMedian = 'ReactionsPerPostLowerThanMedian',
	ConvosightNotInstalledOnAllGroups = 'ConvosightNotInstalledOnAllGroups',
	PostWentLive = 'PostWentLive',
	CampaignInvitation = 'CampaignInvitation',
	WelcomeDeviceNotification = 'WelcomeDeviceNotification',
	UserCampaignTasksReminder = 'UserCampaignTasksReminder',
	ConvosightV2Announcement = 'ConvosightV2Announcement',
	AdminBioInComplete = 'AdminBioInComplete'
}
