import {TreeviewItem} from 'ngx-treeview';
import {Injectable} from '@angular/core';

@Injectable()
export class LanguageService {
	getLanguageList(): TreeviewItem[] {
		const languages = [
			'Afrikaans',
			'Albanian',
			'Amharic',
			'Arabic',
			'Armenian',
			'Azerbaijani',
			'Basque',
			'Belarusian',
			'Bengali',
			'Bosnian',
			'Bulgarian',
			'Catalan',
			'Cebuano',
			'Chinese (Simplified)',
			'Chinese (Traditional)',
			'Corsican',
			'Croatian',
			'Czech',
			'Danish',
			'Dutch',
			'English',
			'Esperanto',
			'Estonian',
			'Finnish',
			'French',
			'Frisian',
			'Galician',
			'Georgian',
			'German',
			'Greek',
			'Gujarati',
			'Haitian Creole',
			'Hausa',
			'Hawaiian',
			'Hebrew',
			'Hindi',
			'Hinglish',
			'Hmong',
			'Hungarian',
			'Icelandic',
			'Igbo',
			'Indonesian',
			'Irish',
			'Italian',
			'Japanese',
			'Javanese',
			'Kannada',
			'Kazakh',
			'Khmer',
			'Korean',
			'Kurdish',
			'Kyrgyz',
			'Lao',
			'Latin',
			'Latvian',
			'Lithuanian',
			'Luxembourgish',
			'Macedonian',
			'Malagasy',
			'Malay',
			'Malayalam',
			'Maltese',
			'Maori',
			'Marathi',
			'Mongolian',
			'Myanmar (Burmese)',
			'Nepali',
			'Norwegian',
			'Nyanja (Chichewa)',
			'Pashto',
			'Persian',
			'Polish',
			'Portuguese (Portugal, Brazil)',
			'Punjabi',
			'Romanian',
			'Russian',
			'Samoan',
			'Scots Gaelic',
			'Serbian',
			'Sesotho',
			'Shona',
			'Sindhi',
			'Sinhala (Sinhalese)',
			'Slovak',
			'Slovenian',
			'Somali',
			'Spanish',
			'Sundanese',
			'Swahili',
			'Swedish',
			'Tagalog (Filipino)',
			'Tajik',
			'Tamil',
			'Telugu',
			'Thai',
			'Turkish',
			'Ukrainian',
			'Urdu',
			'Uzbek',
			'Vietnamese',
			'Welsh',
			'Xhosa',
			'Yiddish',
			'Yoruba',
			'Zulu'
		];
		return languages.map(
			(languageName, i) =>
				new TreeviewItem({
					text: languageName,
					value: languageName
				})
		);
	}
}
