import {TaskTypeEnum, VerificationStatusEnum} from '@sharedModule/models/graph-ql.model';
import {PaymentStatusEnum} from '@sharedModule/enums/payment-status.enum';
import {PostContentTypeEnum} from '@groupAdminModule/models/facebook-post.model';

export class CampaignGroupsModel {
	campaignId: string;
	groupId: string;
	groupName: string;
	pricing: number;
	currency: string;
	groupTaskStatus: string;
	campaignName: string;
	status: string;
	startDateAtUTC: string;
	endDateAtUTC: string;
	primaryObjective: string;
	campaignBriefForCommunityAdmin: string;
	campaignTasks: any;
	isAcceptedByCommunityAdmin: boolean;
	id: string;
	memberCount: number;
	memberEngagementRateUTC: number;
	postEngagementRateUTC: number;
	businessCategory: string;
	state: string;
	groupInstallationStartedAtUTC: string;
	totalKeywordMentions: number;
	totalHashtagMentions: number;
	totalBrandMentions: number;
	iconUrl: string;
	campaignPostEngagementRateLastNinetyDays: number;
	postsEngagementRateLastNinetyDays: number;
	categoryDensity: number;
	fbGroupId: string;
	topTenCities: string;
	location: string;
	averageTopPostsReach: number;
	communityAdminId: string;
	communityAdminName: string;
	communityAdminContact: string;
	communityManagerId: string;
	timezone: string;
	defaultTaskDate: string;
	modeOfCommunication: string;
	modeOfCommunicationVerificationStatus: VerificationStatusEnum;
	paymentStatus: PaymentStatusEnum;
	paymentRemarks: string;
	isPaymentInfoAvailable: string;
	postType: string;
	campaignGroupTaskId: string;
	cohort: string;
	taskId: string;
	userId: string;
	userName: string;
	title: string;
	toBePerformedByUTC: string;
	type: TaskTypeEnum;
	text: string;
	imageUrls: Array<any>;
	videoUrls: Array<any>;
	linkUrls: Array<any>;
	period: string;
	reasonForFailure: string;
	fbPermLink: boolean;
	isPlaceholder: boolean;
	errorFromSource: string;
	timezoneName: string;
}
